"""
Central configuration for the SEC filing assistant.
"""

CHROMA_DATABASE_PATH = "chroma_db"
CHROMA_COLLECTION_NAME = "sec_10k_filings"

DEFAULT_RETRIEVAL_TOP_K = 8
MAX_CONTEXT_CHUNKS = 6

RELEVANCE_THRESHOLD = 0.65

SEMANTIC_SCORE_WEIGHT = 0.55
COMPANY_SCORE_WEIGHT = 0.20
SECTION_SCORE_WEIGHT = 0.15
YEAR_SCORE_WEIGHT = 0.10

COMPANY_ALIAS_PATH = "data/company_aliases.json"

ENABLE_DEBUG_LOGGING = True